export const velaGreen = '#51776B'
export const velaBlue = '#4F7EA8'
export const velaRed = '#a84b61'

export const offBlack = '#3e5052'
export const darkGray = '#777'
export const midGray = '#d3d3d3'
export const lightGray = '#e8e8e8'
export const offWhite = '#f4f4f4'
export const white = '#fafafa'
